[package]
name = "ming-wm"
version = "0.1.0"
edition = "2018"
default-run = "main"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[build-dependencies]
bmp-rust = "0.4.1"
blake2 = { version = "0.10.6", default-features = false }

[dependencies]
blake2 = { version = "0.10.6", default-features = false }
linux_framebuffer = { package = "framebuffer", version = "0.3.1" }
termion = "4.0.3"
rodio = { version = "0.19.0", optional = true }
rand = { version = "0.8.5", optional = true }
audiotags = { version = "0.5.0", optional = true }
bmp-rust = "0.4.1"
dirs = "5.0.1"

[profile.release]
lto = true

[[bin]]
name = "audio_player"
required-features = [ "audiotags", "rand", "rodio" ]
