#!/bin/sh
rm -rf ~/.local/bin/ming_bmps
cp -r ./bmps ~/.local/bin/ming_bmps
rm -f ~/.local/bin/ming_bmps/nimbus-roman/*.bmp
rm -f ~/.local/bin/ming_bmps/nimbus-romano/*.bmp
rm -f ~/.local/bin/ming_bmps/shippori-mincho/*.bmp
rm -f ~/.local/bin/ming_bmps/*1440x842.bmp
rm -f ~/.local/bin/ming_bmps/*.svg
rm -rf ~/.local/bin/ming_docs
cp -r ./docs ~/.local/bin/ming_docs
rm -rf ~/.local/bin/ming_docs/images
cp ./target/release/ming ~/.local/bin/ming
cp ./target/release/mingUtils_Terminal ~/.local/bin/mingUtils_Terminal
cp ./target/release/mingGames_Reversi ~/.local/bin/mingGames_Reversi
cp ./target/release/mingGames_Minesweeper ~/.local/bin/mingGames_Minesweeper
cp ./target/release/mingFiles_File_Explorer ~/.local/bin/mingFiles_File_Explorer
cp ./target/release/mingFiles_Audio_Player ~/.local/bin/mingFiles_Audio_Player
cp ./target/release/mingEditing_Malvim ~/.local/bin/mingEditing_Malvim
cp ./target/release/mingUtils_Draw ~/.local/bin/mingUtils_Draw
