[package]
name = "ming-wm-lib"
version = "0.1.2"
repository = "https://github.com/stjet/ming-wm"
description = "library for building windows for ming-wm in rust"
license = "GPL-3.0-or-later"
edition = "2021"

[dependencies]
